swagger: "2.0"
info:
  description: "Using a Convolutional Neural Net ..."
  version: "0.0.1"
  title: "Opensoundscape Bird Detector"
  contact:
    email: "moore0557@gmail.com"
  license:
    name: "MIT"
    url: "https://github.com/barrymoo/ai4e-example/blob/master/LICENSE"
host: "somewhere_on_azure.com"
basePath: "/v1"
tags:
- name: "birds"
  description: "Making predictions"
schemes:
- "https"
paths:
  /:
    get:
      tags:
      - "birds"
      summary: "Check if the API is up"
      description: "GET / description"
      operationId: "healthCheck"
      responses:
        405:
          description: "Invalid input"
  /detect:
    post:
      tags:
      - "birds"
      summary: "Make prediction on audio"
      description: ""
      operationId: "predictBirds"
      consumes:
      - "application/wav"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "A wav file greater >= 5 s and <= 20 s"
        required: true
        schema:
          type: "string"
          format: bytes
      responses:
        405:
          description: "Invalid input"